name: gateway
description: A gateway server built using the shelf package.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dotenv: ^3.0.0
  get_it: ^7.1.4
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  injectable: ^1.4.1
  catalago:
    path: ../services/catalago
  relatorio:
    path: ../services/relatorio
  venda:
    path: ../services/venda
  core:
    path: ../services/core

dev_dependencies:
  build_runner: ^2.0.5
  injectable_generator: ^1.4.1
  shelf_router_generator: ^1.0.0
