name: catalago
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  core:
    path: ../core
  mysql1: ^0.19.2
  uuid: ^3.0.4
  injectable: ^1.4.1
  
dev_dependencies:
  build_runner: ^2.0.5
  injectable_generator: ^1.4.1
